import Head from 'next/head'
import Image from 'next/image'
import logo from '../assets/logo.svg';
import Experience from '../landing/Experience';
import Header from '../landing/Header';
import Hero from '../landing/Header/Hero';
import HowItWorks from '../landing/HowItWorks';
import Roadmap from '../landing/Roadmap';
import Trade from '../landing/Trade';
import Token from '../landing/Token';
import Faq from '../landing/Faq';
import Footer from '../landing/Footer';

export default function Home() {

  return (
    <div className="font-primary overflow-hidden">
      <Head>
        <title>Lumina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Header />
        <Hero />
        <Experience />
        <Trade />
        <HowItWorks />
        <Roadmap />
        <Token />
        <Faq />
        <Footer />
      </div>
    </div>
  )
}
